name: owncloud
version: 9.0.1ubuntu1
summary: ownCloud
description: ownCloud running on Apache using PHP-FPM with MySQL. This is currently in beta.

apps:
  # Apache daemon
  apache:
    command: apachectl start -DFOREGROUND
    stop-command: apachectl stop
    daemon: simple
    plugs: [listener]

  # PHP-FPM daemon
  php-fpm:
    command: php-fpm start
    stop-command: php-fpm stop
    daemon: forking
    plugs: [listener]

  # MySQL daemon
  mysql:
    command: start_mysql
    stop-command: support-files/mysql.server stop
    daemon: simple
    plugs: [listener]

  # MySQL client
  mysql-client:
    command: mysql --defaults-file=$SNAP_DATA/mysql/root.ini
    plugs: [listener]

  # mDNS daemon
  mdns-publisher:
    command: delay-on-failure mdns-publisher owncloud
    daemon: simple
    plugs: [listener]

  # ownCloud occ command
  occ:
    command: occ
    plugs: [listener]

  # phpinfo() command
  phpinfo:
    command: phpinfo
    plugs: [listener]

plugs:
  listener:
    interface: old-security
    caps: [network-listener]

parts:
  # Copy over some general setup scripts
  setup-scripts:
    plugin: copy
    files:
      src/setup/filesystem.sh: setup/
      src/setup/hw_rating.sh: setup/

  apache:
    plugin: apache
    source: https://github.com/kyrofa/owncloud.git
    source-type: git
    source-tag: 9.0.1

    # The built-in Apache modules to enable
    modules:
      - headers
      - proxy
      - proxy_fcgi
      - setenvif
      - env
      - rewrite
      - mime
      - dir
      - authz_core
      - unixd
      - alias

    # Extra Apache configuration for ownCloud (and PHP)
    # Do not comment out as it places a call to the config in httpd.conf
    extra-configuration: src/owncloud/apache_config

    # Script to run before bringing up Apache
    # Do not comment out as it places a call to the script in envvars
    startup-script: src/owncloud/setup_owncloud

    stage:
      - -htdocs/.git*
      - -conf/extra_configuration
      - -bin/startup_script
    snap:
      - -manual # No need to include the documentation in the .snap
      - -htdocs/.git*
      - -htdocs/.user.ini
      - -conf/extra_configuration
      - -bin/startup_script

  # Copy over our Apache configuration files
  apache-customizations:
    plugin: copy
    after: [apache]
    files:
      src/owncloud/apache_config: conf/extra_configuration
      src/owncloud/userconfigs/platform.conf: conf/userconfigs/
      src/owncloud/userconfigs/custom.conf: conf/userconfigs/
      src/owncloud/setup_owncloud: bin/startup_script

  # Copy over our ownCloud configuration files
  owncloud-customizations:
    plugin: copy
    files:
      src/owncloud/*config.php: htdocs/config/
      src/owncloud/occ: bin/

  php:
    plugin: autotools
    source: http://us1.php.net/get/php-7.0.5.tar.gz/from/this/mirror
    source-type: tar
    install-via: prefix
    configflags:
      - --enable-fpm
      - --disable-cgi
      - --disable-phar
      - --disable-phpdbg
      - --enable-ctype
      - --enable-mbstring
      - --enable-zip
      - --with-pdo-mysql
      - --with-zlib
      - --with-gd
      - --enable-gd-native-ttf
      - --with-jpeg-dir=/usr/lib
      - --with-freetype-dir=/usr/lib
      - --with-curl
      - --with-openssl
      - --with-bz2
      - --with-mcrypt
      - --enable-exif
      - --enable-intl
      - --enable-pcntl
      - --disable-rpath
    stage-packages:
      - libxml2 # Only included here until the OS snap stabilizes
      - libpng12-0
      - libfreetype6
      - libfontconfig1
    build-packages:
      - libfontconfig1-dev
      - libfreetype6-dev
      - libjpeg8-dev
      - libxml2-dev
      - libcurl4-openssl-dev
      - libpng12-dev
      - libbz2-dev
      - libmcrypt-dev

  # Copy over our PHP configuration file.
  php-customizations:
    plugin: copy
    files:
      src/php/php.ini: php/lib/
      src/php/extensions.ini: php/lib/php.conf.d/
      src/php/php-fpm.conf: php/etc/
      src/php/userconfigs/platform.conf: php/userconfigs/
      src/php/userconfigs/custom.conf: php/userconfigs/
      src/php/php-fpm: bin/
      src/php/phpinfo: bin/

  # Download the boost headers for MySQL. Note that the version used may need to
  # be updated if the version of MySQL changes.
  boost:
    plugin: copy
    source: http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz
    files:
      '*': boost/
    snap:
      - -*

  mysql:
    plugin: cmake
    source: https://github.com/kyrofa/mysql-server.git
    source-type: git
    source-branch: feature/support_no_setpriority
    after: [boost]
    configflags:
      - -DWITH_BOOST=$SNAPCRAFT_STAGE/boost
      - -DWITH_INNODB_PAGE_CLEANER_PRIORITY=OFF
      - -DCMAKE_INSTALL_PREFIX=/
      - -DBUILD_CONFIG=mysql_release
      - -DWITH_UNIT_TESTS=OFF
      - -DWITH_EMBEDDED_SERVER=OFF
      - -DWITH_EMBEDDED_SHARED_LIBRARY=OFF
      - -DWITH_ARCHIVE_STORAGE_ENGINE=OFF
      - -DWITH_BLACKHOLE_STORAGE_ENGINE=OFF
      - -DWITH_FEDERATED_STORAGE_ENGINE=OFF
      - -DWITH_PARTITION_STORAGE_ENGINE=OFF
      - -DINSTALL_MYSQLTESTDIR=
    build-packages:
      - wget
      - g++
      - cmake
      - bison
      - libncurses5-dev
      - libaio-dev
    stage:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server
    snap:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server

      # Remove unused binaries that waste space
      - -bin/innochecksum
      - -bin/lz4_decompress
      - -bin/myisam*
      - -bin/mysqladmin
      - -bin/mysqlbinlog
      - -bin/mysql_client_test
      - -bin/mysql_config*
      - -bin/mysqld_multi
      - -bin/mysqldump*
      - -bin/mysqlimport
      - -bin/mysql_install_db
      - -bin/mysql_plugin
      - -bin/mysqlpump
      - -bin/mysql_secure_installation
      - -bin/mysqlshow
      - -bin/mysqlslap
      - -bin/mysql_ssl_rsa_setup
      - -bin/mysqltest
      - -bin/mysql_tzinfo_to_sql
      - -bin/perror
      - -bin/replace
      - -bin/resolveip
      - -bin/resolve_stack_dump
      - -bin/zlib_decompress

  # Copy over our MySQL scripts
  mysql-customizations:
    plugin: copy
    files:
      # This one is what creates the initial database and account for ownCloud.
      src/mysql/start_mysql: bin/
      src/mysql/my.cnf: my.cnf
      src/mysql/mysql.server: support-files/

  mdns-publisher:
    plugin: go
    go-packages: [github.com/kyrofa/mdns-publisher]

  delay-on-failure:
    plugin: copy
    files:
      src/delay-on-failure/delay-on-failure: bin/
